# AUTOGENERATED! DO NOT EDIT! File to edit: ../catdog.ipynb.

# %% auto 0
__all__ = ['a', 'learn', 'categories', 'classify_images']

# %% ../catdog.ipynb 22
from fastai.vision.all import *
import gradio as gr

# %% ../catdog.ipynb 27
learn = load_learner('model.pckl')

# %% ../catdog.ipynb 29
categories = ("Dog", "Cat")
def classify_images(img):
  pred, idx, prob = learn.predict(img)
  return dict(zip(categories, map(float,prob)))

image = gr.Image(height=192, width=192)
label = gr.Label()
